<?php
// doctor/prescription_pdf.php
require_once __DIR__ . '/../includes/auth.php';
require_role('doctor');
require_once __DIR__ . '/../includes/db.php';
require_once __DIR__ . '/../includes/functions.php';
require_once __DIR__ . '/../includes/pdf_helpers.php';

$did = current_user_id();
$prescId = intval($_GET['id'] ?? 0);

if ($prescId <= 0) {
    die("❌ Invalid prescription ID.");
}

// Fetch prescription with patient + doctor info
$stmt = $pdo->prepare("
  SELECT p.id, p.created_at, a.date_time,
         d.name AS doctor_name, d.email AS doctor_email,
         u.name AS patient_name, u.email AS patient_email, u.phone AS patient_phone
  FROM prescriptions p
  JOIN appointments a ON p.appointment_id = a.id
  JOIN users d ON a.doctor_id = d.id
  JOIN users u ON a.patient_id = u.id
  WHERE p.id = :pid AND a.doctor_id = :did
  LIMIT 1
");
$stmt->execute([':pid' => $prescId, ':did' => $did]);
$presc = $stmt->fetch(PDO::FETCH_ASSOC);

if (!$presc) {
    die("❌ Prescription not found or access denied.");
}

// Fetch prescription items (medicines)
$stmt = $pdo->prepare("SELECT * FROM prescription_items WHERE prescription_id=:id");
$stmt->execute([':id' => $prescId]);
$items = $stmt->fetchAll(PDO::FETCH_ASSOC);

if (!$items) {
    die("❌ No medicines found in this prescription.");
}

// Start PDF
$pdf = new FPDF();
$pdf->AddPage();

// Header
pdf_header($pdf);

// Title
$pdf->SetFont('Arial', 'B', 14);
$pdf->Cell(0, 10, 'Prescription', 0, 1, 'C');
$pdf->Ln(5);

// Doctor & Patient Info
$pdf->SetFont('Arial', '', 12);
$pdf->Cell(100, 8, 'Doctor: ' . $presc['doctor_name'], 0, 0);
$pdf->Cell(0, 8, 'Email: ' . $presc['doctor_email'], 0, 1);

$pdf->Cell(100, 8, 'Patient: ' . $presc['patient_name'], 0, 0);
$pdf->Cell(0, 8, 'Phone: ' . ($presc['patient_phone'] ?? 'N/A'), 0, 1);

$pdf->Cell(100, 8, 'Patient Email: ' . $presc['patient_email'], 0, 1);
$pdf->Cell(0, 8, 'Appointment Date: ' . format_datetime($presc['date_time']), 0, 1);
$pdf->Cell(0, 8, 'Prescription Date: ' . format_datetime($presc['created_at']), 0, 1);
$pdf->Ln(10);

// Medicines Table
$pdf->SetFont('Arial', 'B', 12);
$pdf->Cell(60, 10, 'Medicine', 1, 0, 'C');
$pdf->Cell(40, 10, 'Dosage', 1, 0, 'C');
$pdf->Cell(40, 10, 'Duration', 1, 0, 'C');
$pdf->Cell(50, 10, 'Instructions', 1, 1, 'C');

$pdf->SetFont('Arial', '', 12);
foreach ($items as $it) {
    $pdf->Cell(60, 10, $it['medicine'], 1, 0);
    $pdf->Cell(40, 10, $it['dosage'], 1, 0, 'C');
    $pdf->Cell(40, 10, $it['duration'], 1, 0, 'C');
    $pdf->Cell(50, 10, $it['instructions'], 1, 1);
}

// Footer
$pdf->Ln(15);
$pdf->SetFont('Arial', 'I', 11);
$pdf->MultiCell(0, 8, "This prescription is digitally generated by Healsync.\nPlease follow the doctor’s instructions carefully.", 0, 'C');

$pdf->Ln(20);
$pdf->SetFont('Arial', '', 11);
$pdf->Cell(0, 10, 'Authorized by Doctor', 0, 1, 'R');

// Output inline
$pdf->Output('I', 'Prescription_' . $presc['id'] . '.pdf');
